lisa:
 preparation: False # your can set it to False if you want to use the existing avator, it will save time
 bbox_shift: -7
 video_path: "data/video/idle0.mp4"
 audio_clips:
    audio_2: "data/audio/2.mp3"
 
  

