lisa:
 preparation: False # your can set it to False if you want to use the existing avator, it will save time
 bbox_shift: -5
 video_path: "data/video/lisa.mp4"
 audio_clips:
    audio_0: "data/audio/lisa.mp3"
 
  

